spring:
  application:
    name: weg-workshop-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-att
    username: local_user
    password: local_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true